README.md

Added a link to the GitHub pages for the project, corrected typo

Updated top-level README.md with link to docs

---

Samples/DataSources/datasources.html
Samples/DataSources/datasources.js
Samples/Filtering/filtering.html
Samples/Filtering/filtering.js
Samples/Parameters/parameters.html
Samples/Settings/settings.html
Samples/Settings/settings.js
Tutorial/Part_0/MarksSelection.js
Tutorial/Part_0/readme.md
Tutorial/Part_1/MarksSelection.js
Tutorial/Part_1/readme.md
Tutorial/Part_2/MarksSelection.js
Tutorial/Part_2/readme.md
Tutorial/Part_3/MarksSelection.js
Tutorial/Part_3/readme.md
Tutorial/Part_4/MarksSelection.js
Tutorial/Part_4/readme.md
Tutorial/Part_5/MarksSelection.js
Tutorial/Part_5/readme.md
Tutorial/Part_6/MarksSelection.js
Tutorial/Part_6/readme.md
Tutorial/readme.md
community/community_extensions.json
docs/interfaces/analyticsobject.html

Bringing in typo fixes and community extension additions from the last few weeks.

Community Submission

---

_includes/docs_menu.html
docs/trex_manifest.md
docs/trex_security.md

This PR is to add the "Security and Tableau Extensions" topic to the Extensions API Help.  
This content is still pretty drafty. And I'm not sure if this is right information to include.
But it might help people get started.  Feel free to edit away!
.

Doc updates: added HTTPS topic, manifest doc update

---

docs/trex_examples.md

Dave added a fix to the dev branch that adds the correct permission for the datasources sample.

Fix for broken datasource sample.

---

community/community_extensions.json

adding details for the Amazon Product Search extension

Added Amazon Product Search Extension

---

Tutorial/Part_0/readme.md
Tutorial/Part_5/readme.md
docs/trex_getstarted.md
docs/trex_manifest.md
docs/trex_release-notes.md

added 0.10.0 to the Release notes; added context-menu to manifest page, minor updates to tutorial readme files (now that we have a file chooser).

doc updates for the 0.10.0 release

---

docs/trex_release-notes.md

Correcting version number to match library (was 0.12.0)

Update release notes with version 0.12.7

---

docs/trex_create.md

fixing hard-coded version  -latest.js   and fixing reference to AddIn

D45 patch 1

---

_includes/docs_menu.html
docs/trex_events.md
docs/trex_examples.md
docs/trex_getdata.md
docs/trex_known_issues.md
docs/trex_release-notes.md
docs/trex_typescript.md

- Added new topic for TypeScript
- Updated Samples page for TypeScript samples 
- Update Release Notes page
- Fixed Event page (now show objects and the `eventType` supported)
- Added known issue about the time zone when updating date/time parameters 
- Added known issue about `getDataSourcesAsync` being sloooow

Doc updates for v1.3: Added TypeScript support, misc. doc fixes. 

---

README.md
_includes/docs_menu.html
docs/trex_getdata.md
docs/trex_getstarted.md
docs/trex_publish.md
docs/trex_release-notes.md
docs/trex_sandbox_publish.md
docs/trex_sandbox_test.md
docs/trex_typescript.md
docs/ux_extension_gallery.md

@johnDance, @Kovner, @seanmakesgames, @brtal  @LGraber 
Here's the latest update to the docs. I've incorporated the feedback from the first round of reviews. 
I've also updated the README.md file with the sandbox info. 
I added a "This is preliminary information and is subject to change" to "Publish Sandboxed Extensions" (`docs/trex_sandbox_publish.md`). 
Make your edits and corrections! 
Thanks,
Dave

Update to docs for Sandboxed Extensions dev environment

---

docs/trex_debugging.md
docs/trex_getstarted.md
docs/trex_known_issues.md
docs/trex_publish.md
index.html

@johnDance @seanmakesgames @ashwinar @brtal 
I'd like to merge these docs updates with the `dev` branch and then merge the `dev` branch with `master`.   Does anyone see any problems with that? 
That is, is there anything in the `dev` branch that shouldn't be published in the `master` branch?  Or should we cherry pick this doc update to the `master` branch. 
Thanks,

Doc updates for Dashboard Extensions API; Chrome 80 debugging issues

---

community/CommunityManifests/upsetjs.trex
community/community_extensions.json

https://github.com/upsetjs/upsetjs_tableau_extension

add UpSet.js

---

docs/trex_examples.md
docs/trex_release-notes.md
docs/trex_tableau_viz.md

Connecting the dots so users can find the VizImage sample from the docs.

Adding links to VizImage sample

---

docs/trex_release-notes.md
docs/trex_tableau_viz_ref.md
index.html

@filippostableau @alicemhsiao @johnDance @seanmakesgames 
Added doc updates for the v1.8 library.

Adding draft notes for v1.8 release: Tableau Viz updates

---

Tutorial/ReactVersion/yarn.lock

reverse integrate main into dev

---

.github/ISSUE_TEMPLATE/bug_report.md

Created a new issue template to help organize issue-data when issues are created/submitted.

chore:  add issue template for bug reports

---

.github/workflows/main.yml
.gitignore

Create a basic `npm` github action to validate the project builds correctly

create action to validate builds

---

_includes/docs_menu.html
docs/Interaction_Guidelines/ux_build_test.md
docs/Style_Guidelines/ux_fonts.md
docs/trex_events.md
docs/trex_format.md
docs/trex_release-notes.md
docs/trex_sandbox_publish.md
docs/ux_design.md

@bcantoni @johnDance @b-carver @seanmakesgames 
* added topic to describe how to use workbook formatting
* added a link from the Design Guide fonts topic to the workbook formatting topic
* added link to Filtering example (as a event listener example) from event topic
* fixing stray Extension Gallery references

TFSID:1369666 - workbook formatting

---

Samples-Typescript/Formatting/formatting.tsx
Samples/DashboardObjectVisibility/dashboardObjectVisibility.js
Samples/MoveAndResize/moveAndResize.js
Samples/ReplayAnimation/replayAnimation.js

formatting was changed so that npm run build does not error out

React samples working

---

package-lock.json

Running `npm audit` should result in no vulnerabilities.

Update vulnerabilities 6/14/24

---

website/docs/dashext/trex_examples.md
website/docusaurus.config.js
website/package.json
website/yarn.lock

* Updated GA4 ID for tableau.github.io
* Added redirect plugin and redirects for broken links from dev portal

New GA4 ID; redirects

---

website/_analytics.js
website/docs/dashext/trex_examples.md
website/docusaurus.config.js
website/package.json
website/yarn.lock

* GA4 ID for tableau.github.io
* redirect plugin and links

GA4 ID update and redirects for links

---

website/static/api/index.html

cleaning up last "beta" references for viz extensions not included in last commit.

removing beta from text

---

website/docs/dashext/trex_manifest.md
website/docs/trex_known_issues.md
website/docs/vizext/trex_viz_manifest.md

* fix encoding icons (viz extensions)
* add note about naming icons semantically
* add known issue about extension using same  ID, URL, version number.
@wpo-tab

W-18452616, W-18455977

---

website/docs/vizext/trex_viz_create.md
website/docs/vizext/trex_viz_manifest.md
website/static/api/index.html

* minor fixes
* replacing index.html with the version that has the correct links, verbiage

fixing typo, wording, and api index
