_includes/docs_menu.html, docs/trex_api_about.md, docs/trex_contributing.md, docs/trex_create.md, docs/trex_debugging.md, docs/trex_events.md, docs/trex_examples.md, docs/trex_getstarted.md, index.html
Removed a couple of code snippets in the docs that still had "tableau.addIn" 
Removed the Known Issues link that was broken (Known issues moved to the CC site).
=> fixed typos, examples, added descriptions for samples

_includes/head.html
Removed the noindex tag that blocks search engines from showing the Extensions API docs in search results.
=> Removed the meta tag that blocked search engines

docs/trex_create.md
Missed this example in the initial 0.7.0 doc update for schema change.
Added link to logging and troubleshooting topic
=> Updated example .trex file to match new schema

_includes/docs_menu.html
I missed adding this change in the original doc update. Had it locally, but forgot to add it to the PR.
=> Adding Security topic to table of contents

docs/trex_examples.md
Updated instructions for running extensions
=> Added UINamespace sample to the list

Samples/DataSources/DataSources.trex
datasources.js calls dataSource.getConnectionSummariesAsync().
Call fails without declaration in .trex
=> requires full data permission

docs/trex_getstarted.md, docs/trex_release-notes.md
During the beta, the 2018.2 downloads will have the latest updates.
=> Added a link for the Tableau 2018.2 Beta release

docs/trex_create.md, docs/trex_manifest.md
Corrected URL to the manifest schema (too many w's)
=> fix typo in URL for manifest schema

Tutorial/readme.md
Fixed typo of the word 'extension' in third sentence.
=> Typo in readme.md

Tutorial/readme.md, docs/trex_configure.md, docs/trex_getstarted.md, docs/trex_overview.md, docs/trex_release-notes.md
Making the same change to master that we made to the dev branch. 
This one just adds the  "what you can do list" to the overview topic. 
@jz-huang  @Kovner
=> D45 patch what you can do

docs/Interaction_Guidelines/ux_controls_ui_patterns.md
Adding a heading to a column in a table. The Markdown looked fine, but Jekyll didn't recognize it as a table without a heading to the column.
=> Update ux_controls_ui_patterns.md - fixing broken table

assets/js/search.js
When displaying a user's search query on the docs search results page, we should use `textContent` instead of `innerHTML` to prevent XSS per [this OWASP cheatsheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.md#rule-6---populate-the-dom-using-safe-javascript-functions-or-properties).
Note: This change is already in `dev`.
=> [Security] Fix docs XSS vulnerability in search

docs/Interaction_Guidelines/ux_controls_ui_patterns.md, docs/trex_release-notes.md
@nikhillakshman @johnDance  @Kovner 
These are the release notes that have been updated with John's corrections. I also added another item to mention the doc fix for the `SelecttionUpdateType` enum. 
* The documentation for the <a href="https://tableau.github.io/extensions-api/docs/interfaces/worksheet.html#selectmarksbyvalueasync" target="_blank"><code>selectMarksByValueAsync</code></a> method has been corrected. If you are calling the method, be sure to specify the complete namespace for the `SelectionUpdateType` enum that is passed to the method as the `updateType` parameter.  For example, use `tableau.SelectionUpdateType.Replace`, to replace the currently selected marks with the values you specify in the method call. 
And I fixed (I hope!) some broken formatting in the UX Design …
=> updating release notes for the version 1.2 library

docs/trex_create.md, docs/trex_error_handling.md, docs/trex_getstarted.md, docs/trex_known_issues.md, docs/trex_overview.md, docs/trex_release-notes.md, docs/trex_security.md, docs/trex_xss_guidance.md
- changed references to lib files to use new convention
- removed page visibility section from error handling topic and from release notes (added in 2019.1)
- fixed library reference on known issues page to make it clear that  they have to download the lib.
=> updated the library file name with new convention

docs/trex_publish.md
Fixed the typo `fpr` which was there instead of `for` in the last section of the documentation. 
i.e. 
> Community Portal for Dashboard Extensions
=> Fix typo `fpr`

_includes/footer.html, assets/css/main.css, docs/trex_data_access.md, docs/trex_debugging.md, docs/trex_getdata.md, docs/trex_release-notes.md, docs/trex_sandbox_test.md, docs/trex_typescript.md
@ashwinar @johnDance @seanmakesgames @Kovner 
- added release notes for v1.4
- updated Get Data and Access Data topics for OM
- fixes to footer for Legal and Privacy links
- various updates for typos
=> v1.4 doc updates for OM, get data, data access, release notes

docs/trex_release-notes.md
@ashwinar  @nikhillakshman @johnDance 
* Added note about  docs for `clearSelectedMarksAsync()`
* Added bugs fixed in this release section
I didn't mention anything about the library being available on `https://extensions.tableauusercontent.com/` here.  I'm thinking that we should talk about it it terms of compatibility.   I have a rough draft of a topic called "Extensions API Versions and Tableau Compatibility" that isn't in this release.  I'll send that out as a separate doc update.
=> Updates to the v1.4 release notes

docs/trex_known_issues.md
@johnDance 
Cleaned up the wording around the issue with using self-signed certs. I'm thinking that "...dashboard extensions running with self-signed certificates (SSL)..." also sounds awkward.
maybe "...dashboard extensions hosted on web servers that use self-signed certificates (SSL)" ??
=> Remove redundancy in known issue

_config.yml, _includes/head.html, docs/trex_debugging.md, docs/trex_error_handling.md, docs/trex_manifest.md, docs/trex_oauth.md, docs/trex_release-notes.md
@johnDance @seanmakesgames @shinchris @KeshiaRose 
Doc update (belated) for v1.5 library
Changes in this PR:
* Updated "What's New" with links to v1.5 release notes
* Updated debugging desktop instructions for 2021.1 and later (no **Pause before loading**)
* Added sequence diagram for the OAuth flow (using Mermaid gem ) [https://mermaid-js.github.io/](https://mermaid-js.github.io/) 
* Updated `head.html` file to initialize Mermaid
* Updated `_config.yml` to add memaid gem
=> Updating What's new; adding support for Mermaid (diagrams); update debug info

package.json
Disable caching when starting http-server so that changes in JS and HTML files are served upon reload, instead of cached files.
=> "Reload" does not consistently reload JS changes

Samples-Typescript/Parameters/parameters.ts, package-lock.json, package.json, tslint.json
1. Update to usage of 1.6 types
2. npm audit fix
3. prohibit accessing private packages of @tableau/extesions-api-types
=> Update to use version 1.6 of extensions-api-types

docs/trex_release-notes.md
@seanmakesgames @johnDance @Kovner 
patching the release notes with the corrections from the `dev` branch (remove JSON ref, add `getAllDataSourcesAsync`)
=> Update release notes for v1.6

Samples/DataSources/datasources.html
The file is called `datasources.js` and not `dataSources.js`, so the example was not working properly
=> Fixed typo in datasources.html

docs/trex_contributing.md, docs/trex_getstarted.md, index.html
@johnDance @seanmakesgames @Kovner 
Changing the name of the branch to `main` also changed the name of the downloadable `.zip` file. 
Updated links and references to the file and branch name.
=> Update references and links to downloadable .zip file

_includes/guide_menu.html, docs/trex_publish.md, docs/ux_extension_gallery.md
@Craigfis @seanmakesgames @bcantoni 
Changed "Extensions Gallery" to "Tableau Exchange" in the following files:
* trex_publish.md
* ux_extension_gallery.md   // note - I didn't change the file name. I don't think it's too critical at the moment. 
* ux_menu.html  // this is the TOC for the Design Guide
I also updated the links to point to Tableau Exchange.
Note that the Design Guide has some links and information about submitting the extension that still point to the original gallery submission site and still refers to the support email (mailto:extensiongallery@tableau.com)
=> update docs with Tableau Exchange branding

package-lock.json, package.json
Fresh syncs of extension-api are failing to build the react samples.  I found that we were missing react types in our package.json.  Using a fresh build that was failing to build I added those missing react types and now it builds successfully.
=> Adding react types for package.json

_includes/header.html, docs/Interaction_Guidelines/ux_build_test.md, docs/Interaction_Guidelines/ux_controls_ui_patterns.md, docs/Interaction_Guidelines/ux_interaction.md, docs/Style_Guidelines/ux_branding.md, docs/Style_Guidelines/ux_color.md, docs/Style_Guidelines/ux_fonts.md, docs/Style_Guidelines/ux_layout.md, docs/trex_examples.md, docs/trex_release-notes.md, docs/trex_sandbox_publish.md, docs/trex_tableau_viz.md, docs/trex_typescript.md
Found and fixed a bunch of links after running a link checker on the whole site.
=> Fix / update links

docs/trex_release-notes.md
@seanmakesgames @johnDance @elbandito 
Added boilerplate about the 1.8.1 release
=> D45 docs Release Notes for 1.8.1

_includes/docs_menu.html, _includes/footer.html, docs/trex_release-notes.md, docs/trex_tableau_help.md
@mwhagedorn @johnDance @alicemhsiao @wescwu 
- Just added release notes (and links to ref pages)
- Added the About Help topic (standard SFDC)
- Updated privacy link to SDFC policy
=> Doc updates for v1.9. Release notes;About Help topic; privacy URL change

docs/trex_getdata.md, docs/trex_release-notes.md
@johnDance @alicemhsiao @mwhagedorn @stephendeoca @bcantoni 
* updated release notes 1.10
* updated Get Data topic with DataTableReader examples
=> Doc updates for 1.10 

README.md, package-lock.json, package.json
npm audit gives us:
_found 17 vulnerabilities (7 moderate, 3 high, 7 critical) in 435 scanned packages
run `npm audit fix` to fix 15 of them.
1 vulnerability requires semver-major dependency updates.
1 vulnerability requires manual review. See the full report for details._
npm audit fix did:
_fixed 15 of 17 vulnerabilities in 435 scanned packages
1 vulnerability required manual review and could not be updated
1 package update for 1 vulnerability involved breaking changes_
The remaining vulnerability is a moderate level in tslint. TSLint has been deprecated since 2019 and was replaced by typescript-eslint.
=> npm audit: fix critical vulnerabilities

website/docs/dashext/trex_examples.md, website/docs/publish/trex_contributing.md, website/docusaurus.config.js
removing links to the community page until we figure out a new solution
=> fixed link to tutorial, removed community links

website/docs/trex_api_about.md, website/docusaurus.config.js, website/package.json, website/yarn.lock
- Added new GA4 ID to test; docs also use GTM and so ID might be superfluous. 
- upgrade to Docusaurus 3.4.0 from 3.2.
=> Adding new GA4 ID to test if it works for conceptual pages

community/CommunityManifests/MultiSelectParameter.trex, community/community_extensions.json
This pull request adds my MultiSelect Parameter extension to the community extensions list. 
- Added an entry for "My Extension" in the community_extensions.json file.
- Created a manifest file named MultiSelectParameter.trex and placed it in the CommunityManifests folder.
This Extension concatenates selected values from a filter and assigns the result, delimited by '|', to a parameter so that it can be used in Custom SQL Queries or Calculated Fields.
=> Add my extension to community extensions

website/docusaurus.config.js
The Edit this Page link now goes to the proper page in the `gh-pages-dev` branch.
`'https://github.com/tableau/extensions-api/blob/gh-pages-dev/website'`
The link goes to the GitHub web UI, and not the VS Code browser extension (`github.dev`). 
When using `github.dev` in the URL, the link always went to the `main` branch instead of the branch in the URL. 
`'https://github.dev/tableau/extensions-api/blob/gh-pages-dev/website'`
=> updated the editURL to point to the web UI

website/docs/security/trex_sandbox_test.md
Added info (from John Dance) about data security (results returned from a query by a sandboxed extension remain on the client).
=> clarified sandbox query results
